### ISSUE TITLE
Issues and Pull Requests

### ISSUE THREAD

**Issue by LeonardoCardoso** [ebrian/gitdummy#19]
Since issues and PR's are also trackable in public graph, it would be a nice improvement for the next version. If only it's possible.

**Comment by ebrian** [comment]
I think that would be neat, but I don't believe it's directly possible because Issues and PR's are not stored as part of the git repo itself, but instead, the GitHub Issue area. I checked out the GitHub API and did notice that they have endpoints to retrieve things like issues for a repo as well as the associated data, although that would require additional configuration and only work on repos that push to a GitHub origin. At least in my case, Issues/PR's represent less than 1% of my total contributions. Assuming that most people are in the same boat, they would likely not bother with the effort involved in setting up a developer account and an API key to hook to their GitDummy configuration.

I could be wrong though. Thoughts?

**Comment by LeonardoCardoso** [comment]
Well. It could be toilsome. But I'll have a look if there's a simpler way.

-- 
*Leonardo Cardoso*
leocardz.com

<http://git.io/vfgvV>

**Comment by LeonardoCardoso** [comment]
It seems that by https://github.com/stephencelis/ghi is possible. But other 3rd party stuff are required.
