### ISSUE TITLE
Any plans for Gist support?

### ISSUE THREAD

**Issue by graingerkid** [ebrian/gitdummy#20]
Any plans to add Gist support for this? Cool project by the way!

**Comment by ebrian** [comment]
It's been talked about to some degree. See #19 where we were looking at Issues & PRs. My only concern is the value that it brings. GitDummy has always been about reflecting your work, public or private, in your contribution graph. Gists aren't considered a 'contribution' that shows up in your graph because they aren't tied to any particular repository (specifically, they aren't an issue/pr or a commit made on the master branch of a repo). I suppose a Gist only repo could be created...

If we go down this road, I want to go all in and absorb all of the information into a repo. Because there is definitely a way to get Issues, PRs, and Gists from the GH API, loading them into a dummy repo becomes trivial that that point. There would be a little configuration burden that get your API creds into the `repos.json` file and possibly a BC break on the format of the file. I'm definitely not against the idea, but first interested in learning more.

Thoughts?

**Comment by graingerkid** [comment]
No, when you put it like that I think you should leave as is. It's tricky as I use gist more and more for project related stuff.

**Comment by ebrian** [comment]
Yeah. I'm gonna close this out, I think it would introduce too many complexities to what is currently a nice, simple, useful product.
